chore(deps): update dependency @types/node to ^10.17.51 (#151)
* chore(deps): update dependency @types/node to ^10.17.51

* test: fix type errors TS2367

see: https://github.com/microsoft/TypeScript/issues/9998
ex)
Error: test/arraymultimap.ts(52,12): error TS2367: This condition will
always return 'false' since the types '1' and '2' have no overlap.

Co-authored-by: Renovate Bot <bot@renovateapp.com>
Co-authored-by: teppeis <teppeis@gmail.com>